---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 756569002739130368-IPKEWTmFEXL1z9cQnuYjgxwbdh15TPw
:access_token_secret: psGSSBu31SutR5VfYGaOhgp3GjF5tPfcykdMYiBC64Jbg
